### PR TITLE
Get rid of tons of warnings

### PR DESCRIPTION
**Pull request by killme**
Removes / suppresses a lot of warnings.

Warnings not (yet) fixed / questions:
- Unused warning on the following two https://github.com/elBukkit/MagicLib/blob/master/src/main/java/com/elmakers/mine/bukkit/block/Schematic.java#L29
  I'm not really sure what this is, should it just have a getter?
- Dead code in here https://github.com/elBukkit/MagicLib/blob/master/src/main/java/com/elmakers/mine/bukkit/utility/BoundingBox.java#L143 potential bug?
- Bukkit deprecation warnings. Should those just be ignored or actually fixed?

### CODE REVIEW

**Comment by NathanWolf** [comment]
Wow, awesome, thank you! Some of this was... embarrassing.

There is one change I want to review, though, in ConfigurationUtils- the switch to Map<?, ?> from Map<String, Object> seemed kind of odd.

**Comment by killme** [comment]
No problem.
Regarding that code, unlike in most places I actually avoided using `@SuppressWarnings` there and just worked around it. This removes the needs for unchecked casts.
Regarding the questions in the PR, did you fix that already in another commit or should I still have a look at that?

**Comment by NathanWolf** [comment]
Oops sorry, I mean to respond to those! So:
1. The Schematic.offset is (I think) saved to a schematic by worldedit, and basically shows where the player was when it was saved. I don't use it for anything, but a getter wouldn't hurt- I can add that.
2. I'll have to take a closer look at that one, that particular method is kind of important so if there's a potential bug there I'll take a look.
3. Well that depends- I actually use a lot of deprecated Bukkit methods out of necessity. Bukkit has/had a bad habit of marking things deprecated when they're actually still needed and useful (see: Player.updateInventory/playSound(String)). If there's anything that is deprecated and can actually be replaced by a newer/different API method without any behavior change, I'm fine with that though!

**Comment by killme** [comment]
1. s/fixed/suppressed/

**Comment by NathanWolf** [comment]
Ah, then yes :)

I switched from Eclipse to IntelliJ a while back, and while I'm mostly very happy I find IntelliJ is weird about warnings. It no longer warns me about some things, like deprecation usage. But then it considers problems like mis-named parameters _in the javadocs_ as _errors_. :\

**Pull request merged**
